import os

class Config(object):
    DEBUG = False
    TESTING = False

    SECRET_KEY = "SECRET_KEY"

    SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"
    SQLALCHEMY_TRACK_MODIFICATIONS = "SQLALCHEMY_TRACK_MODIFICATIONS"

    UPLOADS = "UPLOADS"

    ALLOWED_IMAGE_EXTENTIONS = ["png", "jpg", "jpeg", "gif"]

    SESSION_COOKIE_SECURE = "SESSION_COOKIE_SECURE "

class ProductionConfig(Config):
    pass


class DevelopmentConfig(Config):
    DEBUG = True

    SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"

    UPLOADS = "UPLOADS"

    SESSION_COOKIE_SECURE = "SESSION_COOKIE_SECURE"

class TestingConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"
    UPLOADS = "UPLOADS"

    SESSION_COOKIE_SECURE = "SESSION_COOKIE_SECURE"
